apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-log-helm.fullname" . }}
  labels:
    app.kubernetes.io/name: python-log-helm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "python-log-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "python-log-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configMapRef }}
        volumeMounts:
        - mountPath: "/var/log"
          name: py-logs
      volumes:
        - name: py-logs
          persistentVolumeClaim:
            claimName: py-logs            
