apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: py-logs
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

  