apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-log-helm.fullname" . }}
  labels:
    app.kubernetes.io/name: python-log-helm
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: python-log-helm
